# Generated by Django 5.2.16 on 2026-08-17 15:17

from django.db import migrations, models


def mark_existing_pocketcasts_completions_as_inferred(apps, schema_editor):
    """Conservatively flag pre-existing Pocket Casts completion dates as inferred.

    Every completed Pocket Casts podcast created before this migration got its
    end_date from the importer's synthetic estimation logic (publish+duration
    on first import, or hash-distributed placement) - there was no other
    source of completion timestamps. We can't distinguish which specific rows
    were estimated vs. anchored after the fact, so the safe default is to
    mark them all as inferred rather than implying false precision.
    """
    Podcast = apps.get_model("app", "Podcast")
    Podcast.objects.filter(
        item__source="pocketcasts", end_date__isnull=False
    ).update(is_end_date_inferred=True)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0157_rewrite_old_img_none_placeholder_after_widening"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpodcast",
            name="is_end_date_inferred",
            field=models.BooleanField(
                default=False,
                help_text="True when end_date is a synthetic estimate (e.g. derived from publication time + duration, or distributed across the sync window) rather than a timestamp backed by real provider listening evidence.",
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="is_end_date_inferred",
            field=models.BooleanField(
                default=False,
                help_text="True when end_date is a synthetic estimate (e.g. derived from publication time + duration, or distributed across the sync window) rather than a timestamp backed by real provider listening evidence.",
            ),
        ),
        migrations.RunPython(
            mark_existing_pocketcasts_completions_as_inferred,
            migrations.RunPython.noop,
        ),
    ]
