# Generated by Django 5.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0157_rewrite_old_img_none_placeholder_after_widening"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaybackProgressChange",
            fields=[
                (
                    "sequence_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("item_id", models.PositiveBigIntegerField()),
                (
                    "operation",
                    models.CharField(
                        choices=[("upsert", "Upsert"), ("delete", "Delete")],
                        max_length=6,
                    ),
                ),
                ("media_type", models.CharField(max_length=32)),
                ("source", models.CharField(max_length=32)),
                ("media_id", models.CharField(max_length=500)),
                ("season_number", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                ("ids", models.JSONField(blank=True, default=dict)),
                ("position_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("source_client_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_progress_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_id"],
                "indexes": [
                    models.Index(
                        fields=["user", "sequence_id"],
                        name="playchg_user_seq_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="playchg_user_created_idx",
                    ),
                ],
            },
        ),
    ]
