# Generated by Django 5.2.16 on 2026-08-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0158_podcast_end_date_inferred"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deletedmedia",
            name="media_id",
            field=models.CharField(max_length=500),
        ),
    ]
