# Generated by Django 5.2.9 on 2026-08-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0159_alter_studio_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="imdb_rating",
            field=models.FloatField(
                blank=True,
                help_text="Average rating value from IMDB public datasets",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="imdb_rating_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Rating count from IMDB public datasets",
                null=True,
            ),
        ),
    ]
