# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0159_playbackprogresschange"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedMediaMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_media_memberships",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_media_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="savedmedia_user_updated_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item"),
                        name="savedmedia_unique_user_item",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedMediaChange",
            fields=[
                (
                    "sequence_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("item_id", models.PositiveBigIntegerField()),
                (
                    "operation",
                    models.CharField(
                        choices=[("add", "Add"), ("remove", "Remove")],
                        max_length=6,
                    ),
                ),
                ("media_type", models.CharField(max_length=32)),
                ("source", models.CharField(max_length=32)),
                ("media_id", models.CharField(max_length=500)),
                ("ids", models.JSONField(blank=True, default=dict)),
                ("source_client_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_media_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_id"],
                "indexes": [
                    models.Index(
                        fields=["user", "sequence_id"],
                        name="savedchg_user_seq_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="savedchg_user_created_idx",
                    ),
                ],
            },
        ),
    ]
