# Generated by Django 5.2.16 on 2026-08-18 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0159_alter_deletedmedia_media_id"),
        ("app", "0160_item_imdb_rating_item_imdb_rating_count"),
    ]

    operations = []
