# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0160_savedmediamembership_savedmediachange"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="playbackprogresschange",
            index=models.Index(
                fields=["created_at"],
                name="playchg_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedmediachange",
            index=models.Index(
                fields=["created_at"],
                name="savedchg_created_idx",
            ),
        ),
    ]
