# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0161_sync_change_retention_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="playbackprogress",
            index=models.Index(
                fields=["user", "id"],
                name="playprog_user_id_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedmediamembership",
            index=models.Index(
                fields=["user", "id"],
                name="savedmedia_user_id_idx",
            ),
        ),
    ]
