# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Max, Q

_BATCH_SIZE = 500
_COMPLETED = "completed"


def _flush(model, rows):
    """Bulk-create one bounded current-state batch without emitting signals."""
    if not rows:
        return
    model.objects.bulk_create(
        rows,
        batch_size=_BATCH_SIZE,
        ignore_conflicts=True,
    )
    rows.clear()


def backfill_current_watched_state(apps, schema_editor):
    """Seed current watched truth from existing movie and exact episode history."""
    Movie = apps.get_model("app", "Movie")
    Episode = apps.get_model("app", "Episode")
    WatchedState = apps.get_model("app", "WatchedState")

    pending = []
    movies = (
        Movie.objects.filter(
            Q(status=_COMPLETED)
            | Q(end_date__isnull=False)
            | Q(plays__isnull=False)
        )
        .values("pk", "user_id", "item_id", "end_date")
        .annotate(latest_play=Max("plays__end_date"))
        .order_by("pk")
    )
    for row in movies.iterator(chunk_size=_BATCH_SIZE):
        pending.append(
            WatchedState(
                user_id=row["user_id"],
                item_id=row["item_id"],
                watched=True,
                watched_at=row["latest_play"] or row["end_date"],
                source_client_id="",
            )
        )
        if len(pending) >= _BATCH_SIZE:
            _flush(WatchedState, pending)
    _flush(WatchedState, pending)

    episodes = (
        Episode.objects.filter(status=_COMPLETED)
        .values("related_season__user_id", "item_id")
        .annotate(watched_at=Max("end_date"))
        .order_by("related_season__user_id", "item_id")
    )
    for row in episodes.iterator(chunk_size=_BATCH_SIZE):
        pending.append(
            WatchedState(
                user_id=row["related_season__user_id"],
                item_id=row["item_id"],
                watched=True,
                watched_at=row["watched_at"],
                source_client_id="",
            )
        )
        if len(pending) >= _BATCH_SIZE:
            _flush(WatchedState, pending)
    _flush(WatchedState, pending)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0162_stable_snapshot_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched", models.BooleanField(default=False)),
                ("watched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_client_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_states",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "id"],
                        name="watchstate_user_id_idx",
                    ),
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="watchstate_user_updated_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item"),
                        name="watchedstate_unique_user_item",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WatchedStateChange",
            fields=[
                (
                    "sequence_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("item_id", models.PositiveBigIntegerField()),
                ("watched", models.BooleanField()),
                ("media_type", models.CharField(max_length=32)),
                ("source", models.CharField(max_length=32)),
                ("media_id", models.CharField(max_length=500)),
                ("season_number", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                ("ids", models.JSONField(blank=True, default=dict)),
                ("watched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_client_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_state_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_id"],
                "indexes": [
                    models.Index(
                        fields=["user", "sequence_id"],
                        name="watchchg_user_seq_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="watchchg_user_created_idx",
                    ),
                    models.Index(
                        fields=["created_at"],
                        name="watchchg_created_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            backfill_current_watched_state,
            migrations.RunPython.noop,
        ),
    ]
