# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0163_watchedstate_watchedstatechange"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="watchedstate",
            index=models.Index(
                fields=["user", "watched", "id"],
                name="watchstate_user_watched_id_idx",
            ),
        ),
    ]
