/* This file is generated by `cargo xtask contract generate`. Do not edit. */

export interface HealthResponse {
  readonly status: string;
  readonly version: string;
}

export interface ProblemActionDto {
  readonly id: string;
  readonly label: string;
}

export interface ViolationDto {
  readonly actual?: null | string;
  readonly code: string;
  readonly expected: string;
  readonly pointer: string;
  readonly reason: string;
}

export interface ProblemDetails {
  readonly actual?: null | string;
  readonly capability_id: CapabilityId;
  readonly code: ProblemCode;
  readonly correlation_id: string;
  readonly detail: string;
  readonly next_actions: ReadonlyArray<ProblemActionDto>;
  readonly param?: null | string;
  readonly retryability: string;
  readonly safe_state: string;
  readonly status: number;
  readonly title: string;
  readonly type: string;
  readonly violations: ReadonlyArray<ViolationDto>;
}

export interface ReceiptCommittedEvent {
  readonly capability_id: "observation.accept";
  readonly committed_at: string;
  readonly correlation_id: string;
  readonly observation_id: string;
  readonly operation_id: string;
  readonly receipt_id: string;
  readonly resolution: "unresolved";
}

export interface ReceiptCommittedEnvelope {
  readonly id: string;
  readonly event: "receiptCommitted";
  readonly data: ReceiptCommittedEvent;
}

// prettier-ignore
export type CapabilityId =
  | "client.enroll"
  | "correction.chain.append"
  | "correction.chain.inspect"
  | "credential.revoke"
  | "credential.rotate"
  | "identity.identifier.attach"
  | "identity.record.create"
  | "identity.review.defer"
  | "identity.review.inspect"
  | "identity.review.resolve"
  | "identity.review.resume"
  | "listener.configure"
  | "node.initialize"
  | "observation.accept"
  | "portability.workspace.export"
  | "portability.workspace.restore"
  | "portability.workspace.verify"
  | "profile.select"
  | "receipt.replay"
  | "system.capabilities.discover"
  | "system.health";

// prettier-ignore
export type CapabilityBody =
  | "b0"
  | "b1"
  | "b2"
  | "b3";

// prettier-ignore
export type ContractState =
  | "finalized"
  | "reserved";

// prettier-ignore
export type RuntimeAvailability =
  | "fixture_only"
  | "guarded"
  | "implemented"
  | "later_body";

// prettier-ignore
export type ProblemCode =
  | "capability_unavailable"
  | "contract_drift"
  | "forbidden"
  | "idempotency_conflict"
  | "invalid_identifier"
  | "invalid_observation"
  | "invalid_time"
  | "receipt_not_found"
  | "validation_failed";

export interface CapabilityMetadata {
  readonly id: CapabilityId;
  readonly contractBody: CapabilityBody;
  readonly runtimeBody: CapabilityBody;
  readonly contractState: ContractState;
  readonly runtimeAvailability: RuntimeAvailability;
  readonly surfaceProfile: string;
}

export const CAPABILITY_REGISTRY = [
  {
    id: "client.enroll",
    contractBody: "b1",
    runtimeBody: "b2",
    contractState: "finalized",
    runtimeAvailability: "fixture_only",
    surfaceProfile: "b1_http_fixture",
  },
  {
    id: "correction.chain.append",
    contractBody: "b3",
    runtimeBody: "b3",
    contractState: "reserved",
    runtimeAvailability: "later_body",
    surfaceProfile: "later_b3",
  },
  {
    id: "correction.chain.inspect",
    contractBody: "b3",
    runtimeBody: "b3",
    contractState: "reserved",
    runtimeAvailability: "later_body",
    surfaceProfile: "later_b3",
  },
  {
    id: "credential.revoke",
    contractBody: "b1",
    runtimeBody: "b2",
    contractState: "finalized",
    runtimeAvailability: "fixture_only",
    surfaceProfile: "b1_http_fixture",
  },
  {
    id: "credential.rotate",
    contractBody: "b1",
    runtimeBody: "b2",
    contractState: "finalized",
    runtimeAvailability: "fixture_only",
    surfaceProfile: "b1_http_fixture",
  },
  {
    id: "identity.identifier.attach",
    contractBody: "b2",
    runtimeBody: "b2",
    contractState: "reserved",
    runtimeAvailability: "later_body",
    surfaceProfile: "later_b2",
  },
  {
    id: "identity.record.create",
    contractBody: "b2",
    runtimeBody: "b2",
    contractState: "reserved",
    runtimeAvailability: "later_body",
    surfaceProfile: "later_b2",
  },
  {
    id: "identity.review.defer",
    contractBody: "b2",
    runtimeBody: "b2",
    contractState: "reserved",
    runtimeAvailability: "later_body",
    surfaceProfile: "later_b2",
  },
  {
    id: "identity.review.inspect",
    contractBody: "b2",
    runtimeBody: "b2",
    contractState: "reserved",
    runtimeAvailability: "later_body",
    surfaceProfile: "later_b2",
  },
  {
    id: "identity.review.resolve",
    contractBody: "b2",
    runtimeBody: "b2",
    contractState: "reserved",
    runtimeAvailability: "later_body",
    surfaceProfile: "later_b2",
  },
  {
    id: "identity.review.resume",
    contractBody: "b2",
    runtimeBody: "b2",
    contractState: "reserved",
    runtimeAvailability: "later_body",
    surfaceProfile: "later_b2",
  },
  {
    id: "listener.configure",
    contractBody: "b1",
    runtimeBody: "b2",
    contractState: "finalized",
    runtimeAvailability: "fixture_only",
    surfaceProfile: "b1_listener",
  },
  {
    id: "node.initialize",
    contractBody: "b1",
    runtimeBody: "b2",
    contractState: "finalized",
    runtimeAvailability: "fixture_only",
    surfaceProfile: "b1_http_fixture",
  },
  {
    id: "observation.accept",
    contractBody: "b1",
    runtimeBody: "b2",
    contractState: "finalized",
    runtimeAvailability: "fixture_only",
    surfaceProfile: "b1_http_fixture",
  },
  {
    id: "portability.workspace.export",
    contractBody: "b3",
    runtimeBody: "b3",
    contractState: "reserved",
    runtimeAvailability: "guarded",
    surfaceProfile: "later_b3",
  },
  {
    id: "portability.workspace.restore",
    contractBody: "b3",
    runtimeBody: "b3",
    contractState: "reserved",
    runtimeAvailability: "guarded",
    surfaceProfile: "later_b3",
  },
  {
    id: "portability.workspace.verify",
    contractBody: "b3",
    runtimeBody: "b3",
    contractState: "reserved",
    runtimeAvailability: "guarded",
    surfaceProfile: "later_b3",
  },
  {
    id: "profile.select",
    contractBody: "b1",
    runtimeBody: "b2",
    contractState: "finalized",
    runtimeAvailability: "fixture_only",
    surfaceProfile: "b1_http_fixture",
  },
  {
    id: "receipt.replay",
    contractBody: "b1",
    runtimeBody: "b2",
    contractState: "finalized",
    runtimeAvailability: "fixture_only",
    surfaceProfile: "b1_receipt_replay",
  },
  {
    id: "system.capabilities.discover",
    contractBody: "b1",
    runtimeBody: "b1",
    contractState: "finalized",
    runtimeAvailability: "fixture_only",
    surfaceProfile: "b1_http_fixture",
  },
  {
    id: "system.health",
    contractBody: "b1",
    runtimeBody: "b0",
    contractState: "finalized",
    runtimeAvailability: "implemented",
    surfaceProfile: "health",
  },
] as const satisfies ReadonlyArray<CapabilityMetadata>;

export const RECEIPT_STREAM_CONTRACT = {
  path: "/api/v1/receipts/stream",
  eventName: "receiptCommitted",
  capabilityId: "listener.configure",
  requiredScope: "receipt_read",
  runtimeAvailability: "fixture_only",
  maximumReplayBatch: 100,
  retryPolicy: "bounded_client_backoff",
} as const;

export class FastiContractParseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "FastiContractParseError";
  }
}

type JsonObject = Record<string, unknown>;

const HEALTH_ALLOWED = ["status", "version"] as const;
const HEALTH_REQUIRED = ["status", "version"] as const;
// prettier-ignore
const CAPABILITY_IDS = ["client.enroll", "correction.chain.append", "correction.chain.inspect", "credential.revoke", "credential.rotate", "identity.identifier.attach", "identity.record.create", "identity.review.defer", "identity.review.inspect", "identity.review.resolve", "identity.review.resume", "listener.configure", "node.initialize", "observation.accept", "portability.workspace.export", "portability.workspace.restore", "portability.workspace.verify", "profile.select", "receipt.replay", "system.capabilities.discover", "system.health"] as const;
// prettier-ignore
const PROBLEM_CODES = ["capability_unavailable", "contract_drift", "forbidden", "idempotency_conflict", "invalid_identifier", "invalid_observation", "invalid_time", "receipt_not_found", "validation_failed"] as const;
// prettier-ignore
const PROBLEM_ALLOWED = ["actual", "capability_id", "code", "correlation_id", "detail", "next_actions", "param", "retryability", "safe_state", "status", "title", "type", "violations"] as const;
// prettier-ignore
const PROBLEM_REQUIRED = ["capability_id", "code", "correlation_id", "detail", "next_actions", "retryability", "safe_state", "status", "title", "type", "violations"] as const;
const ACTION_ALLOWED = ["id", "label"] as const;
const ACTION_REQUIRED = ["id", "label"] as const;
// prettier-ignore
const VIOLATION_ALLOWED = ["actual", "code", "expected", "pointer", "reason"] as const;
const VIOLATION_REQUIRED = ["code", "expected", "pointer", "reason"] as const;
// prettier-ignore
const RECEIPT_ALLOWED = ["capability_id", "committed_at", "correlation_id", "observation_id", "operation_id", "receipt_id", "resolution"] as const;
// prettier-ignore
const RECEIPT_REQUIRED = ["capability_id", "committed_at", "correlation_id", "observation_id", "operation_id", "receipt_id", "resolution"] as const;
const CORRELATION_ID = new RegExp("^req_[0-9a-f]{32}$");
const RECEIPT_ID = new RegExp("^rcp_[0-9a-f]{32}$");
const OPERATION_ID = new RegExp("^op_[0-9a-f]{32}$");
const OBSERVATION_ID = new RegExp("^obs_[0-9a-f]{32}$");
// prettier-ignore
const RFC3339_INSTANT = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;

// prettier-ignore
export function parseHealthResponse(value: unknown): HealthResponse {
  const object = exactObject(value, HEALTH_ALLOWED, HEALTH_REQUIRED, "HealthResponse");
  stringField(object, "status", "HealthResponse");
  stringField(object, "version", "HealthResponse");
  return object as unknown as HealthResponse;
}

// prettier-ignore
export function parseProblemDetails(value: unknown): ProblemDetails {
  const object = exactObject(value, PROBLEM_ALLOWED, PROBLEM_REQUIRED, "ProblemDetails");
  for (const field of [
    "type",
    "title",
    "detail",
    "code",
    "capability_id",
    "safe_state",
    "retryability",
    "correlation_id",
  ] as const) {
    stringField(object, field, "ProblemDetails");
  }
  knownStringField(object, "capability_id", CAPABILITY_IDS, "ProblemDetails");
  knownStringField(object, "code", PROBLEM_CODES, "ProblemDetails");
  integerField(object, "status", "ProblemDetails", 0, 65_535);
  nullableStringField(object, "param", "ProblemDetails");
  nullableStringField(object, "actual", "ProblemDetails");
  arrayField(object, "next_actions", "ProblemDetails").forEach(parseProblemAction);
  arrayField(object, "violations", "ProblemDetails").forEach(parseViolation);
  return object as unknown as ProblemDetails;
}

// prettier-ignore
export function parseReceiptCommittedEvent(value: unknown): ReceiptCommittedEvent {
  const object = exactObject(value, RECEIPT_ALLOWED, RECEIPT_REQUIRED, "ReceiptCommittedEvent");
  exactString(object, "capability_id", "observation.accept", "ReceiptCommittedEvent");
  exactString(object, "resolution", "unresolved", "ReceiptCommittedEvent");
  patternString(object, "correlation_id", CORRELATION_ID, "ReceiptCommittedEvent");
  patternString(object, "receipt_id", RECEIPT_ID, "ReceiptCommittedEvent");
  patternString(object, "operation_id", OPERATION_ID, "ReceiptCommittedEvent");
  patternString(object, "observation_id", OBSERVATION_ID, "ReceiptCommittedEvent");
  patternString(object, "committed_at", RFC3339_INSTANT, "ReceiptCommittedEvent");
  return object as unknown as ReceiptCommittedEvent;
}

// prettier-ignore
function parseProblemAction(value: unknown): ProblemActionDto {
  const object = exactObject(value, ACTION_ALLOWED, ACTION_REQUIRED, "ProblemActionDto");
  stringField(object, "id", "ProblemActionDto");
  stringField(object, "label", "ProblemActionDto");
  return object as unknown as ProblemActionDto;
}

// prettier-ignore
function parseViolation(value: unknown): ViolationDto {
  const object = exactObject(value, VIOLATION_ALLOWED, VIOLATION_REQUIRED, "ViolationDto");
  for (const field of ["code", "pointer", "reason", "expected"] as const) {
    stringField(object, field, "ViolationDto");
  }
  nullableStringField(object, "actual", "ViolationDto");
  return object as unknown as ViolationDto;
}

// prettier-ignore
function exactObject(
  value: unknown,
  allowed: readonly string[],
  required: readonly string[],
  label: string,
): JsonObject {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new FastiContractParseError(`${label} must be an object`);
  }
  const object = value as JsonObject;
  for (const key of Object.keys(object)) {
    if (!allowed.includes(key)) {
      throw new FastiContractParseError(`${label} contains unknown field ${key}`);
    }
  }
  for (const key of required) {
    if (!(key in object)) {
      throw new FastiContractParseError(`${label} is missing required field ${key}`);
    }
  }
  return object;
}

function stringField(object: JsonObject, field: string, label: string): string {
  const value = object[field];
  if (typeof value !== "string") {
    throw new FastiContractParseError(`${label}.${field} must be a string`);
  }
  return value;
}

// prettier-ignore
function knownStringField(
  object: JsonObject,
  field: string,
  allowed: readonly string[],
  label: string,
): void {
  if (!allowed.includes(stringField(object, field, label))) {
    throw new FastiContractParseError(`${label}.${field} has an unsupported value`);
  }
}

// prettier-ignore
function exactString(
  object: JsonObject,
  field: string,
  expected: string,
  label: string,
): void {
  if (stringField(object, field, label) !== expected) {
    throw new FastiContractParseError(`${label}.${field} has an unsupported value`);
  }
}

// prettier-ignore
function patternString(
  object: JsonObject,
  field: string,
  pattern: RegExp,
  label: string,
): void {
  if (!pattern.test(stringField(object, field, label))) {
    throw new FastiContractParseError(`${label}.${field} has an invalid format`);
  }
}

// prettier-ignore
function nullableStringField(object: JsonObject, field: string, label: string): void {
  const value = object[field];
  if (value !== undefined && value !== null && typeof value !== "string") {
    throw new FastiContractParseError(`${label}.${field} must be a string or null`);
  }
}

// prettier-ignore
function integerField(
  object: JsonObject,
  field: string,
  label: string,
  minimum: number,
  maximum: number,
): void {
  const value = object[field];
  if (typeof value !== "number" || !Number.isInteger(value) || value < minimum || value > maximum) {
    throw new FastiContractParseError(`${label}.${field} must be an integer in range`);
  }
}

// prettier-ignore
function arrayField(object: JsonObject, field: string, label: string): unknown[] {
  const value = object[field];
  if (!Array.isArray(value)) {
    throw new FastiContractParseError(`${label}.${field} must be an array`);
  }
  return value;
}
