packages:
  - "apps/*"
  - "packages/*"
overrides:
  "brace-expansion@5.0.8": "5.0.9"
  "svelte-check@4.7.6>typescript": "6.0.3"
allowBuilds:
  "@scarf/scarf": false
  core-js: false
  libxmljs2: true
  nx: true
