# Generated by Django 5.2.16 on 2026-08-17 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0023_plexwebhookshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration token',
                'verbose_name_plural': 'Integration tokens',
                'indexes': [models.Index(fields=['user', 'created_at'], name='integration_user_id_419014_idx')],
            },
        ),
    ]
