# Generated by Django 5.2.16 on 2026-08-17 15:45

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0024_integrationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEventReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_event_id', models.CharField(db_index=True, max_length=255)),
                ('payload_digest', models.CharField(max_length=64)),
                ('response_status_code', models.IntegerField(default=200)),
                ('response_body', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),

                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_receipts', to='integrations.integrationtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration event receipt',
                'verbose_name_plural': 'Integration event receipts',
                'constraints': [models.UniqueConstraint(fields=('user', 'client_event_id'), name='unique_user_client_event_id')],
            },
        ),
    ]
