export * from "./mock-data.js";

import type { WorkbenchPreferences } from "./types.js";

export function createDefaultWorkbenchPreferences(): WorkbenchPreferences {
  return {
    sidebarCollapsed: false,
    sidebarHidden: false,
    navItems: [
      {
        id: "home",
        label: "Chronicle",
        category: "primary",
        visible: true,
        pinned: true,
        order: 0,
      },
      {
        id: "discover",
        label: "Discover",
        category: "primary",
        visible: true,
        pinned: true,
        order: 1,
      },
      {
        id: "library",
        label: "Library",
        category: "primary",
        visible: true,
        pinned: true,
        order: 2,
      },
      {
        id: "tv_shows",
        label: "TV Shows",
        category: "media",
        visible: true,
        pinned: false,
        order: 3,
      },
      {
        id: "movies",
        label: "Movies",
        category: "media",
        visible: true,
        pinned: false,
        order: 4,
      },
      {
        id: "anime",
        label: "Anime",
        category: "media",
        visible: true,
        pinned: false,
        order: 5,
      },
      {
        id: "manga",
        label: "Manga",
        category: "media",
        visible: true,
        pinned: false,
        order: 6,
      },
      {
        id: "games",
        label: "Games",
        category: "media",
        visible: true,
        pinned: false,
        order: 7,
      },
      {
        id: "books",
        label: "Books",
        category: "media",
        visible: true,
        pinned: false,
        order: 8,
      },
      {
        id: "comics",
        label: "Comics",
        category: "media",
        visible: true,
        pinned: false,
        order: 9,
      },
      {
        id: "music",
        label: "Music",
        category: "media",
        visible: true,
        pinned: false,
        order: 10,
      },
      {
        id: "podcasts",
        label: "Podcasts",
        category: "media",
        visible: true,
        pinned: false,
        order: 11,
      },
      {
        id: "calendar",
        label: "Calendar",
        category: "library",
        visible: true,
        pinned: true,
        order: 12,
      },
      {
        id: "collection",
        label: "Collections",
        category: "library",
        visible: true,
        pinned: false,
        order: 13,
      },
      {
        id: "reconciliation",
        label: "Review Inbox",
        category: "utilities",
        visible: true,
        pinned: true,
        order: 14,
      },
      {
        id: "connections",
        label: "Connections",
        category: "utilities",
        visible: true,
        pinned: true,
        order: 15,
      },
      {
        id: "settings",
        label: "Settings",
        category: "utilities",
        visible: true,
        pinned: true,
        order: 16,
      },
    ],
    contextMenuItems: [
      {
        id: "toggle_watched",
        label: "Mark as Watched",
        visible: true,
        order: 0,
      },
      {
        id: "update_progress",
        label: "Update Progress...",
        visible: true,
        order: 1,
      },
      {
        id: "add_collection",
        label: "Add to Collection...",
        visible: true,
        order: 2,
      },
      {
        id: "rate_review",
        label: "Post Rating & Review...",
        visible: true,
        order: 3,
      },
      {
        id: "view_details",
        label: "View Full Details",
        visible: true,
        order: 4,
      },
    ],
  };
}
