import type {
  MediaRecord,
  ChronicleOccurrence,
  ReconciliationCase,
  CustomFieldDefinition,
  ScopedApiToken,
  OidcConfiguration,
  AppriseNotificationConfig,
  ThemeSettings,
  NavItemConfig,
  ContextMenuItemConfig,
  WorkbenchPreferences,
} from "./types.js";

export const SAMPLE_RECORDS: MediaRecord[] = [
  {
    id: "rec_01K89Z00LuckyShow",
    title: "Lucky",
    mediaKind: "show",
    releaseYear: 2026,
    airDates: "July 14, 2026 – Aug 18, 2026",
    format: "TV Miniseries",
    statusText: "Ended",
    country: "United States of America",
    languages: ["English"],
    runtimeMinutes: 318,
    overview:
      "When a multi-million-dollar heist goes sideways, con artist Lucky is forced to go on the run. Pursued by both the FBI and a ruthless crime boss, Lucky must fight for her life—and a way out.",
    posterUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&q=80",
    backdropUrl:
      "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1280&q=80",
    status: "watching",
    userRating: 9,
    communityRating: {
      score: 6.7,
      votes: 11316,
      source: "TMDB",
    },
    progressEpisodes: 2,
    totalEpisodes: 7,
    progressSeconds: 5760,
    totalDurationSeconds: 19080,
    displaySource: "tmdb_tv",
    tags: ["Heist", "Suspense", "Con Artist", "Action"],
    genres: ["Drama", "Crime", "Thriller"],
    studios: [
      "Apple Studios",
      "Hello Sunshine",
      "J. V. T. Films",
      "Lady Killer Productions",
    ],
    lastActivityAt: "2026-08-23T21:40:00Z",
    externalIds: [
      {
        namespace: "tmdb_tv",
        value: "278624",
        status: "matched",
        source: "tmdb_api",
        url: "https://www.themoviedb.org/tv/278624",
      },
      {
        namespace: "tvdb_series",
        value: "449120",
        status: "matched",
        source: "tvdb_api",
        url: "https://thetvdb.com/series/lucky-2026",
      },
      {
        namespace: "imdb_title",
        value: "tt30849281",
        status: "matched",
        source: "plex_webhook",
        url: "https://www.imdb.com/title/tt30849281",
      },
    ],
    userNotes:
      "Anya Taylor-Joy carries the suspense with tremendous charisma. Episode 2 chase scene in Lisbon was masterfully filmed.",
    seasons: [
      {
        seasonNumber: 1,
        title: "Miniseries",
        posterUrl:
          "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&q=80",
        episodeCount: 7,
        episodes: [
          {
            id: "ep_lucky_1",
            number: 1,
            seasonNumber: 1,
            title: "The Heist at Sunrise",
            overview:
              "Lucky plans her most ambitious job yet at an offshore casino.",
            airDate: "2026-07-14",
            durationSeconds: 2700,
            watched: true,
            watchedAt: "2026-08-23T20:00:00Z",
            userRating: 9,
          },
          {
            id: "ep_lucky_2",
            number: 2,
            seasonNumber: 1,
            title: "Lisbon Contingency",
            overview:
              "The getaway goes wrong when an unexpected informant blows their cover.",
            airDate: "2026-07-21",
            durationSeconds: 3060,
            watched: true,
            watchedAt: "2026-08-23T21:40:00Z",
            userRating: 9,
          },
          {
            id: "ep_lucky_3",
            number: 3,
            seasonNumber: 1,
            title: "Safe Houses & Counterfeits",
            overview:
              "Seeking refuge with an estranged contact in the Pyrenees.",
            airDate: "2026-07-28",
            durationSeconds: 2640,
            watched: false,
          },
          {
            id: "ep_lucky_4",
            number: 4,
            seasonNumber: 1,
            title: "The Double Cross",
            overview: "FBI special agents close the perimeter.",
            airDate: "2026-08-04",
            durationSeconds: 2820,
            watched: false,
          },
          {
            id: "ep_lucky_5",
            number: 5,
            seasonNumber: 1,
            title: "Blood Money",
            overview: "The crime syndicate issues a worldwide bounty.",
            airDate: "2026-08-11",
            durationSeconds: 2760,
            watched: false,
          },
          {
            id: "ep_lucky_6",
            number: 6,
            seasonNumber: 1,
            title: "Cornered",
            overview: "A desperate stand in Marseille harbor.",
            airDate: "2026-08-18",
            durationSeconds: 2880,
            watched: false,
          },
          {
            id: "ep_lucky_7",
            number: 7,
            seasonNumber: 1,
            title: "Clean Break",
            overview: "The final showdown and escape plan.",
            airDate: "2026-08-18",
            durationSeconds: 3120,
            watched: false,
          },
        ],
      },
    ],
    cast: [
      {
        id: "cast_1",
        name: "Anya Taylor-Joy",
        characterName: "Lucky Armstrong",
        profileUrl:
          "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=185&q=80",
      },
      {
        id: "cast_2",
        name: "Annette Bening",
        characterName: "Judith Armstrong",
        profileUrl:
          "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=185&q=80",
      },
      {
        id: "cast_3",
        name: "Clifton Collins Jr.",
        characterName: "Detective Ortiz",
        profileUrl:
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=185&q=80",
      },
      {
        id: "cast_4",
        name: "Timothy Olyphant",
        characterName: "Agent Vance Miller",
        profileUrl:
          "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=185&q=80",
      },
      {
        id: "cast_5",
        name: "Drew Starkey",
        characterName: "Tyler",
        profileUrl:
          "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=185&q=80",
      },
    ],
    crew: [
      { id: "crew_1", name: "Jonathan van Tulleken", role: "Director" },
      { id: "crew_2", name: "Marissa Jo Cerar", role: "Showrunner & Writer" },
      { id: "crew_3", name: "Reece Shearsmith", role: "Executive Producer" },
    ],
  },
  {
    id: "rec_01K89Z01FrierenAnime",
    title: "Frieren: Beyond Journey's End",
    originalTitle: "葬送のフリーレン (Sousou no Frieren)",
    mediaKind: "anime",
    releaseYear: 2023,
    airDates: "Sep 29, 2023 – Mar 22, 2024",
    format: "TV Series (28 eps)",
    statusText: "Finished Airing",
    country: "Japan",
    languages: ["Japanese", "English Sub"],
    runtimeMinutes: 672,
    overview:
      "The adventure is over, but life goes on for an elf mage just beginning to learn what living is all about. The demon king has been defeated, and the victorious hero party returns home before disbanding.",
    posterUrl:
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&q=80",
    backdropUrl:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1280&q=80",
    status: "watching",
    userRating: 10,
    communityRating: {
      score: 9.34,
      votes: 420800,
      source: "MyAnimeList #1 Top Rated",
    },
    progressEpisodes: 24,
    totalEpisodes: 28,
    displaySource: "mal_anime",
    tags: [
      "Fantasy",
      "Slice of Life",
      "Elves",
      "Adventure",
      "Magic",
      "Shounen",
    ],
    genres: ["Adventure", "Drama", "Fantasy"],
    studios: ["Madhouse", "TOHO animation", "Shogakukan"],
    lastActivityAt: "2026-08-24T20:15:00Z",
    collectionName: "Frieren Franchise",
    externalIds: [
      {
        namespace: "mal_anime",
        value: "52991",
        status: "matched",
        source: "anibridge_pack",
        url: "https://myanimelist.net/anime/52991",
      },
      {
        namespace: "anilist_anime",
        value: "154587",
        status: "matched",
        source: "anilist_api",
        url: "https://anilist.co/anime/154587",
      },
      {
        namespace: "kitsu_anime",
        value: "46001",
        status: "matched",
        source: "simkl_import",
        url: "https://kitsu.io/anime/46001",
      },
      {
        namespace: "tmdb_tv",
        value: "209867",
        status: "matched",
        source: "tmdb_api",
        url: "https://www.themoviedb.org/tv/209867",
      },
      {
        namespace: "imdb_title",
        value: "tt22238804",
        status: "matched",
        source: "simkl_import",
        url: "https://www.imdb.com/title/tt22238804",
      },
    ],
    userNotes:
      "Exemplary pacing, sound design, and emotional restraint. Season 1 finale was perfection.",
    seasons: [
      {
        seasonNumber: 1,
        title: "Season 1",
        posterUrl:
          "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&q=80",
        episodeCount: 28,
        episodes: [
          {
            id: "ep_frieren_1",
            number: 1,
            seasonNumber: 1,
            title: "The Journey's End",
            durationSeconds: 1440,
            watched: true,
            watchedAt: "2026-08-10T19:00:00Z",
            userRating: 10,
          },
          {
            id: "ep_frieren_2",
            number: 2,
            seasonNumber: 1,
            title: "It Didn't Have to Be Magic...",
            durationSeconds: 1440,
            watched: true,
            watchedAt: "2026-08-11T20:00:00Z",
            userRating: 10,
          },
          {
            id: "ep_frieren_24",
            number: 24,
            seasonNumber: 1,
            title: "Perfect Replication",
            durationSeconds: 1440,
            watched: true,
            watchedAt: "2026-08-24T20:15:00Z",
            userRating: 10,
          },
          {
            id: "ep_frieren_25",
            number: 25,
            seasonNumber: 1,
            title: "A Fatal Vulnerability",
            durationSeconds: 1440,
            watched: false,
          },
          {
            id: "ep_frieren_26",
            number: 26,
            seasonNumber: 1,
            title: "The Height of Magic",
            durationSeconds: 1440,
            watched: false,
          },
          {
            id: "ep_frieren_27",
            number: 27,
            seasonNumber: 1,
            title: "An Era of Humans",
            durationSeconds: 1440,
            watched: false,
          },
          {
            id: "ep_frieren_28",
            number: 28,
            seasonNumber: 1,
            title: "It Would Be Embarrassing When We Meet Again",
            durationSeconds: 1440,
            watched: false,
          },
        ],
      },
    ],
    cast: [
      {
        id: "cast_fr_1",
        name: "Atsumi Tanezaki",
        characterName: "Frieren (Voice)",
      },
      { id: "cast_fr_2", name: "Kana Ichinose", characterName: "Fern (Voice)" },
      {
        id: "cast_fr_3",
        name: "Chiaki Kobayashi",
        characterName: "Stark (Voice)",
      },
      {
        id: "cast_fr_4",
        name: "Nobuhiko Okamoto",
        characterName: "Himmel (Voice)",
      },
    ],
    crew: [
      {
        id: "crew_fr_1",
        name: "Keiichirou Saitou",
        role: "Director (Bocchi the Rock!)",
      },
      { id: "crew_fr_2", name: "Tomohiro Suzuki", role: "Series Composition" },
      {
        id: "crew_fr_3",
        name: "Evan Call",
        role: "Music Composer (Violet Evergarden)",
      },
    ],
  },
  {
    id: "rec_01K89Z03DunePartTwo",
    title: "Dune: Part Two",
    mediaKind: "movie",
    releaseYear: 2024,
    airDates: "March 1, 2024",
    format: "Feature Film (4K IMAX)",
    statusText: "Released",
    country: "United States",
    languages: ["English", "Chakobsa"],
    runtimeMinutes: 166,
    overview:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.",
    posterUrl:
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=600&q=80",
    backdropUrl:
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=1280&q=80",
    status: "completed",
    userRating: 10,
    communityRating: {
      score: 8.5,
      votes: 560000,
      source: "IMDb #74 Top 250",
    },
    progressSeconds: 9960,
    totalDurationSeconds: 9960,
    displaySource: "tmdb_movie",
    tags: ["Sci-Fi", "Epic", "Desert", "Prophecy", "IMAX"],
    genres: ["Science Fiction", "Adventure", "Action"],
    studios: ["Legendary Pictures", "Warner Bros. Pictures"],
    collectionName: "Denis Villeneuve's Dune Collection",
    lastActivityAt: "2026-08-18T22:30:00Z",
    externalIds: [
      {
        namespace: "tmdb_movie",
        value: "693134",
        status: "matched",
        source: "tmdb_api",
        url: "https://www.themoviedb.org/movie/693134",
      },
      {
        namespace: "imdb_title",
        value: "tt15239678",
        status: "matched",
        source: "jellyfin_webhook",
        url: "https://www.imdb.com/title/tt15239678",
      },
      {
        namespace: "trakt_movie",
        value: "dune-part-two-2024",
        status: "matched",
        source: "trakt_import",
        url: "https://trakt.tv/movies/dune-part-two-2024",
      },
    ],
    userNotes:
      "Masterpiece of scale, visual rhythm, and sound design. The sandworm mounting sequence is unforgettable.",
    cast: [
      {
        id: "cast_dune_1",
        name: "Timothée Chalamet",
        characterName: "Paul Atreides",
      },
      { id: "cast_dune_2", name: "Zendaya", characterName: "Chani" },
      {
        id: "cast_dune_3",
        name: "Rebecca Ferguson",
        characterName: "Lady Jessica",
      },
      {
        id: "cast_dune_4",
        name: "Austin Butler",
        characterName: "Feyd-Rautha Harkonnen",
      },
      { id: "cast_dune_5", name: "Javier Bardem", characterName: "Stilgar" },
    ],
    crew: [
      {
        id: "crew_dune_1",
        name: "Denis Villeneuve",
        role: "Director & Screenplay",
      },
      {
        id: "crew_dune_2",
        name: "Greig Fraser",
        role: "Director of Photography",
      },
      { id: "crew_dune_3", name: "Hans Zimmer", role: "Music Composer" },
    ],
  },
  {
    id: "rec_01K89Z02SeveranceShow",
    title: "Severance",
    mediaKind: "show",
    releaseYear: 2022,
    airDates: "Feb 18, 2022 – Present",
    format: "TV Series",
    statusText: "Returning Series",
    country: "United States",
    languages: ["English"],
    runtimeMinutes: 520,
    overview:
      "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.",
    posterUrl:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80",
    backdropUrl:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1280&q=80",
    status: "watching",
    userRating: 9,
    communityRating: {
      score: 8.7,
      votes: 215000,
      source: "IMDb",
    },
    progressEpisodes: 9,
    totalEpisodes: 19,
    displaySource: "tvdb",
    tags: ["Sci-Fi", "Psychological Thriller", "Mystery", "Corporate Dystopia"],
    genres: ["Drama", "Mystery", "Sci-Fi & Fantasy"],
    studios: ["Apple Studios", "Red Hour Productions", "Endeavor Content"],
    lastActivityAt: "2026-08-22T21:40:00Z",
    externalIds: [
      {
        namespace: "tmdb_tv",
        value: "95396",
        status: "matched",
        source: "tmdb_api",
        url: "https://www.themoviedb.org/tv/95396",
      },
      {
        namespace: "tvdb_series",
        value: "371980",
        status: "matched",
        source: "tvdb_api",
        url: "https://thetvdb.com/series/severance",
      },
      {
        namespace: "imdb_title",
        value: "tt11280740",
        status: "matched",
        source: "plex_webhook",
        url: "https://www.imdb.com/title/tt11280740",
      },
    ],
    userNotes:
      "Lumon Industries architecture and cinematography is mesmerizing.",
    cast: [
      { id: "cast_sev_1", name: "Adam Scott", characterName: "Mark Scout" },
      {
        id: "cast_sev_2",
        name: "Patricia Arquette",
        characterName: "Harmony Cobel",
      },
      {
        id: "cast_sev_3",
        name: "John Turturro",
        characterName: "Irving Bailiff",
      },
      {
        id: "cast_sev_4",
        name: "Christopher Walken",
        characterName: "Burt Goodman",
      },
    ],
    crew: [
      {
        id: "crew_sev_1",
        name: "Ben Stiller",
        role: "Director & Executive Producer",
      },
      { id: "crew_sev_2", name: "Dan Erickson", role: "Creator & Writer" },
    ],
  },
  {
    id: "rec_01K89Z05EldenRingGame",
    title: "Elden Ring: Shadow of the Erdtree",
    mediaKind: "game",
    releaseYear: 2024,
    airDates: "June 21, 2024",
    format: "Video Game (Action RPG)",
    statusText: "Released",
    country: "Japan",
    languages: ["English", "Japanese"],
    runtimeMinutes: 3000,
    overview:
      "Guided by Empyrean Miquella, players are summoned to the Land of Shadow, a place obscured by the Erdtree where goddess Marika first set foot.",
    posterUrl:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80",
    backdropUrl:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1280&q=80",
    status: "watching",
    userRating: 10,
    communityRating: {
      score: 9.5,
      votes: 185000,
      source: "Steam (Overwhelmingly Positive)",
    },
    progressSeconds: 144000,
    totalDurationSeconds: 180000,
    displaySource: "steam_app",
    tags: [
      "Action RPG",
      "Soulslike",
      "Open World",
      "Dark Fantasy",
      "Difficult",
    ],
    genres: ["Action RPG", "Adventure"],
    studios: ["FromSoftware", "Bandai Namco Entertainment"],
    collectionName: "Elden Ring Franchise",
    lastActivityAt: "2026-08-25T01:00:00Z",
    externalIds: [
      {
        namespace: "steam_app",
        value: "2778580",
        status: "matched",
        source: "steam_api",
        url: "https://store.steampowered.com/app/2778580",
      },
      {
        namespace: "rawg_game",
        value: "elden-ring-shadow-of-the-erdtree",
        status: "matched",
        source: "rawg_api",
        url: "https://rawg.io/games/elden-ring-shadow-of-the-erdtree",
      },
      {
        namespace: "gog_product",
        value: "1928374",
        status: "matched",
        source: "user_override",
      },
    ],
    userNotes:
      "Messmer the Impaler boss fight is one of FromSoftware's finest combat designs.",
    crew: [
      { id: "crew_er_1", name: "Hidetaka Miyazaki", role: "Director" },
      {
        id: "crew_er_2",
        name: "George R. R. Martin",
        role: "Worldbuilding Mythology",
      },
    ],
  },
  {
    id: "rec_01K89Z04NeuromancerBook",
    title: "Neuromancer",
    mediaKind: "book",
    releaseYear: 1984,
    airDates: "July 1, 1984",
    format: "Novel (Paperback)",
    statusText: "Published",
    country: "United States",
    languages: ["English"],
    runtimeMinutes: 380,
    overview:
      "Case had been the sharpest data-thief in the business, until he crossed the wrong people and they crippled his nervous system. A mysterious employer recruits him for a last-chance run at an unthinkably powerful AI.",
    posterUrl:
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80",
    status: "completed",
    userRating: 9,
    communityRating: {
      score: 4.15,
      votes: 380000,
      source: "Goodreads",
    },
    displaySource: "google_books",
    tags: [
      "Cyberpunk",
      "Classic Sci-Fi",
      "Artificial Intelligence",
      "Sprawl Trilogy",
    ],
    genres: ["Science Fiction", "Cyberpunk"],
    studios: ["Ace Books", "Gollancz"],
    collectionName: "Sprawl Trilogy",
    lastActivityAt: "2026-08-15T18:00:00Z",
    externalIds: [
      {
        namespace: "isbn_13",
        value: "9780441569595",
        status: "matched",
        source: "open_library",
        url: "https://openlibrary.org/isbn/9780441569595",
      },
      {
        namespace: "google_books",
        value: "vH_lAgAAQBAJ",
        status: "matched",
        source: "google_books_api",
      },
    ],
    userNotes:
      "'The sky above the port was the color of television, tuned to a dead channel.' Iconic opening line.",
    crew: [{ id: "crew_nm_1", name: "William Gibson", role: "Author" }],
  },
  {
    id: "rec_01K89Z06HikaruNoGoManga",
    title: "Hikaru no Go",
    originalTitle: "ヒカルの碁",
    mediaKind: "manga",
    releaseYear: 1998,
    airDates: "1998 – 2003",
    format: "Manga (23 Volumes)",
    statusText: "Completed",
    country: "Japan",
    languages: ["Japanese", "English"],
    overview:
      "Hikaru Shindo discovers an ancient Go board in his grandfather's attic, awakening the spirit of Fujiwara-no-Sai, a legendary Go master from the Heian period.",
    posterUrl:
      "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=600&q=80",
    status: "watching",
    userRating: 9,
    communityRating: {
      score: 8.65,
      votes: 45000,
      source: "MyAnimeList",
    },
    progressEpisodes: 12,
    totalEpisodes: 23,
    displaySource: "mal_manga",
    tags: ["Go", "Game", "Supernatural", "Friendship", "Shounen"],
    genres: ["Game", "Shounen", "Supernatural"],
    studios: ["Weekly Shonen Jump", "Shueisha", "VIZ Media"],
    externalIds: [
      {
        namespace: "mal_manga",
        value: "23",
        status: "matched",
        source: "anibridge_pack",
        url: "https://myanimelist.net/manga/23",
      },
      {
        namespace: "anilist_manga",
        value: "30023",
        status: "matched",
        source: "anilist_api",
      },
    ],
    crew: [
      { id: "crew_hg_1", name: "Yumi Hotta", role: "Story Writer" },
      {
        id: "crew_hg_2",
        name: "Takeshi Obata",
        role: "Illustrator (Death Note)",
      },
    ],
  },
  {
    id: "rec_01K89Z07DarkSideMoonMusic",
    title: "The Dark Side of the Moon",
    mediaKind: "music",
    releaseYear: 1973,
    airDates: "March 1, 1973",
    format: "Album (Vinyl LP)",
    statusText: "Released",
    country: "United Kingdom",
    languages: ["English"],
    runtimeMinutes: 43,
    overview:
      "The eighth studio album by the English rock band Pink Floyd, exploring themes of conflict, greed, time, death, and mental illness.",
    posterUrl:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80",
    status: "completed",
    userRating: 10,
    communityRating: {
      score: 4.88,
      votes: 95000,
      source: "RateYourMusic #3 All-Time",
    },
    displaySource: "musicbrainz",
    tags: ["Progressive Rock", "Psychedelic Rock", "Concept Album", "Classic"],
    genres: ["Progressive Rock", "Art Rock"],
    studios: ["Harvest Records", "Abbey Road Studios"],
    externalIds: [
      {
        namespace: "musicbrainz_album",
        value: "a74b1b7f-71a5-4011-9441-d0b5e4122711",
        status: "matched",
        source: "musicbrainz_api",
        url: "https://musicbrainz.org/release-group/a74b1b7f-71a5-4011-9441-d0b5e4122711",
      },
      {
        namespace: "discogs_release",
        value: "1873013",
        status: "matched",
        source: "discogs_api",
      },
    ],
    crew: [
      { id: "crew_pf_1", name: "Pink Floyd", role: "Artist" },
      { id: "crew_pf_2", name: "Alan Parsons", role: "Sound Engineer" },
    ],
  },
];

export const SAMPLE_CHRONICLE: ChronicleOccurrence[] = [
  {
    id: "occ_01K89Z11",
    recordId: "rec_01K89Z05EldenRingGame",
    title: "Elden Ring: Shadow of the Erdtree",
    mediaKind: "game",
    posterUrl:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80",
    timestamp: "2026-08-25T01:00:00Z",
    progressPercentage: 80,
    durationMinutes: 120,
    deviceName: "Gaming Desktop (Linux/Wayland)",
    clientName: "Desktop MPRIS / Steam Hook",
    isRewatch: false,
    userRating: 10,
  },
  {
    id: "occ_01K89Z12",
    recordId: "rec_01K89Z01FrierenAnime",
    title: "Frieren: Beyond Journey's End",
    episodeTitle: "Perfect Replication",
    seasonNumber: 1,
    episodeNumber: 24,
    mediaKind: "anime",
    posterUrl:
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&q=80",
    timestamp: "2026-08-24T20:15:00Z",
    progressPercentage: 100,
    durationMinutes: 24,
    deviceName: "Living Room NuvioTV",
    clientName: "Nuvio Ingest B7",
    isRewatch: false,
    userRating: 10,
  },
  {
    id: "occ_01K89Z10",
    recordId: "rec_01K89Z00LuckyShow",
    title: "Lucky",
    episodeTitle: "Lisbon Contingency",
    seasonNumber: 1,
    episodeNumber: 2,
    mediaKind: "show",
    posterUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&q=80",
    timestamp: "2026-08-23T21:40:00Z",
    progressPercentage: 100,
    durationMinutes: 51,
    deviceName: "Living Room Apple TV",
    clientName: "Apple TV+ / Plex Webhook",
    isRewatch: false,
    userRating: 9,
  },
  {
    id: "occ_01K89Z13",
    recordId: "rec_01K89Z02SeveranceShow",
    title: "Severance",
    episodeTitle: "The We We Are",
    seasonNumber: 1,
    episodeNumber: 9,
    mediaKind: "show",
    posterUrl:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80",
    timestamp: "2026-08-22T21:40:00Z",
    progressPercentage: 100,
    durationMinutes: 48,
    deviceName: "Bedroom Kodi",
    clientName: "Jellyfin Webhook",
    isRewatch: false,
    userRating: 9,
  },
  {
    id: "occ_01K89Z14",
    recordId: "rec_01K89Z03DunePartTwo",
    title: "Dune: Part Two",
    mediaKind: "movie",
    posterUrl:
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=600&q=80",
    timestamp: "2026-08-18T22:30:00Z",
    progressPercentage: 100,
    durationMinutes: 166,
    deviceName: "Living Room Apple TV",
    clientName: "Plex Webhook",
    isRewatch: true,
    userRating: 10,
  },
];

export const SAMPLE_RECONCILIATION: ReconciliationCase[] = [
  {
    id: "rec_case_01",
    recordId: "rec_01K89Z01FrierenAnime",
    title: "Frieren Mini Anime (Sousou no Frieren: ●● no Mahou)",
    mediaKind: "anime",
    suppliedIds: [
      {
        namespace: "kitsu_anime",
        value: "48102",
        status: "matched",
        source: "simkl_import",
        url: "https://kitsu.io/anime/48102",
      },
      {
        namespace: "imdb_title",
        value: "tt29273618",
        status: "matched",
        source: "simkl_import",
        url: "https://www.imdb.com/title/tt29273618",
      },
    ],
    candidateId: "cand_01",
    candidateTitle: "Sousou no Frieren: Marumaru no Mahou",
    candidateNamespace: "mal_anime",
    candidateExternalId: "56885",
    candidatePosterUrl:
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&q=80",
    matchingReasons: [
      "Exact Kitsu-linked crosswalk match",
      "Identical air schedule timeframe (Oct 2023 - Mar 2024)",
      "Shared native Japanese title (●●の魔法)",
      "Identical production studio (Madhouse)",
    ],
    conflictingFactors: [
      "MAL classifies this as a separate 11-episode Special release",
      "TVDB groups these mini-episodes into Season 0 (Specials)",
    ],
    status: "open",
  },
];

export const SAMPLE_DISCOVER_TRENDING: MediaRecord[] = [
  SAMPLE_RECORDS[0], // Lucky
  SAMPLE_RECORDS[1], // Frieren
  SAMPLE_RECORDS[2], // Dune 2
  SAMPLE_RECORDS[3], // Severance
  SAMPLE_RECORDS[4], // Elden Ring
  SAMPLE_RECORDS[6], // Hikaru no Go
];

export const SAMPLE_CUSTOM_FIELDS: CustomFieldDefinition[] = [
  {
    key: "games.gog_product_id",
    label: "GOG Product ID",
    targetType: "game",
    valueType: "identifier",
    registeredNamespace: "gog_product",
    isFilterable: true,
  },
  {
    key: "books.hardcover_id",
    label: "Hardcover Book ID",
    targetType: "book",
    valueType: "identifier",
    registeredNamespace: "hardcover_book",
    isFilterable: true,
  },
  {
    key: "custom.personal_archive_shelf",
    label: "Physical Archive Shelf",
    targetType: "all",
    valueType: "string",
    isFilterable: true,
  },
];

export const SAMPLE_TOKENS: ScopedApiToken[] = [
  {
    id: "tok_01",
    name: "Living Room NuvioTV Ingest",
    tokenPrefix: "fst_pat_9a2f4c1e...",
    scopes: ["chronicle:write", "progress:read_write"],
    createdAt: "2026-08-20T10:00:00Z",
    lastUsedAt: "2026-08-25T01:00:00Z",
  },
  {
    id: "tok_02",
    name: "Home Assistant Local Bridge",
    tokenPrefix: "fst_pat_b17c8802...",
    scopes: ["chronicle:read", "metadata:read"],
    createdAt: "2026-08-15T14:30:00Z",
    lastUsedAt: "2026-08-24T22:00:00Z",
  },
];

export const SAMPLE_OIDC_CONFIG: OidcConfiguration = {
  enabled: false,
  issuerUrl: "https://auth.internal.scrobble.dev/application/o/fasti/",
  clientId: "fasti-living-chronicle",
  clientSecret: "",
  redirectUri: "http://127.0.0.1:8420/api/v1/auth/oidc/callback",
  autoProvisionUsers: true,
};

export const SAMPLE_APPRISE_CONFIG: AppriseNotificationConfig = {
  enabled: true,
  urls: ["discord://webhook_id/webhook_token", "pover://user_key@token_key"],
  notifyOnReviewRequired: true,
  notifyOnSyncError: true,
  notifyOnMilestone: true,
};

export const DEFAULT_THEME_SETTINGS: ThemeSettings = {
  mode: "light",
  accentColor: "#066fd1",
  fontFamily: "sans-serif",
  themeBase: "slate",
  cornerRadius: 1,
  density: "normal",
  fontSize: "md",
};

export const DEFAULT_NAV_ITEMS: NavItemConfig[] = [
  // Primary
  {
    id: "home",
    label: "Home",
    category: "primary",
    visible: true,
    pinned: true,
    order: 0,
  },
  {
    id: "discover",
    label: "Discover",
    category: "primary",
    visible: true,
    pinned: true,
    order: 1,
  },

  // Media
  {
    id: "tv_shows",
    label: "TV Shows",
    category: "media",
    visible: true,
    pinned: false,
    order: 2,
  },
  {
    id: "tv_seasons",
    label: "TV Seasons",
    category: "media",
    visible: true,
    pinned: false,
    order: 3,
  },
  {
    id: "movies",
    label: "Movies",
    category: "media",
    visible: true,
    pinned: false,
    order: 4,
  },
  {
    id: "anime",
    label: "Anime",
    category: "media",
    visible: true,
    pinned: false,
    order: 5,
  },
  {
    id: "manga",
    label: "Manga",
    category: "media",
    visible: true,
    pinned: false,
    order: 6,
  },
  {
    id: "games",
    label: "Games",
    category: "media",
    visible: true,
    pinned: false,
    order: 7,
  },
  {
    id: "books",
    label: "Books",
    category: "media",
    visible: true,
    pinned: false,
    order: 8,
  },
  {
    id: "comics",
    label: "Comics",
    category: "media",
    visible: true,
    pinned: false,
    order: 9,
  },
  {
    id: "board_games",
    label: "Board Games",
    category: "media",
    visible: true,
    pinned: false,
    order: 10,
  },
  {
    id: "music",
    label: "Music",
    category: "media",
    visible: true,
    pinned: false,
    order: 11,
  },
  {
    id: "podcasts",
    label: "Podcasts",
    category: "media",
    visible: true,
    pinned: false,
    order: 12,
  },

  // Library
  {
    id: "calendar",
    label: "Calendar",
    category: "library",
    visible: true,
    pinned: false,
    order: 13,
  },
  {
    id: "collection",
    label: "Collection",
    category: "library",
    visible: true,
    pinned: false,
    order: 14,
  },
  {
    id: "custom",
    label: "Custom",
    category: "library",
    visible: true,
    pinned: false,
    order: 15,
  },
  {
    id: "history",
    label: "History",
    category: "library",
    visible: true,
    pinned: false,
    order: 16,
  },
  {
    id: "lists",
    label: "Lists",
    category: "library",
    visible: true,
    pinned: false,
    order: 17,
  },
  {
    id: "statistics",
    label: "Statistics",
    category: "library",
    visible: true,
    pinned: false,
    order: 18,
  },
  {
    id: "tags",
    label: "Tags",
    category: "library",
    visible: true,
    pinned: false,
    order: 19,
  },

  // Utilities
  {
    id: "reconciliation",
    label: "Identity Review",
    category: "utilities",
    visible: true,
    pinned: false,
    order: 20,
  },
  {
    id: "sources",
    label: "Sources",
    category: "utilities",
    visible: true,
    pinned: false,
    order: 21,
  },
  {
    id: "settings",
    label: "Settings",
    category: "utilities",
    visible: true,
    pinned: true,
    order: 22,
  },
];

export const DEFAULT_CONTEXT_MENU_ITEMS: ContextMenuItemConfig[] = [
  { id: "view", label: "View Details", visible: true, order: 0 },
  { id: "watched", label: "Mark as Seen / Unplayed", visible: true, order: 1 },
  {
    id: "progress",
    label: "Update Progress & Episodes",
    visible: true,
    order: 2,
  },
  { id: "watchlist", label: "Watchlist Toggle", visible: true, order: 3 },
  { id: "collection", label: "Add to Collection...", visible: true, order: 4 },
  { id: "review", label: "Rate & Personal Review...", visible: true, order: 5 },
  { id: "edit_tags", label: "Manage Tags...", visible: true, order: 6 },
  {
    id: "manage_ids",
    label: "Inspect External Claim IDs...",
    visible: true,
    order: 7,
  },
  {
    id: "reconcile",
    label: "Review & Reconcile Identity...",
    visible: true,
    order: 8,
  },
];

export const DEFAULT_WORKBENCH_PREFERENCES: WorkbenchPreferences = {
  sidebarCollapsed: false,
  sidebarHidden: false,
  navItems: DEFAULT_NAV_ITEMS,
  contextMenuItems: DEFAULT_CONTEXT_MENU_ITEMS,
};
