// This file is generated by `cargo xtask contract generate`. Do not edit.

use fasti_application::CapabilityKey;

/// Returns the registry-owned public ID for one internal application key.
pub const fn public_capability_id(key: CapabilityKey) -> &'static str {
    match key {
        CapabilityKey::AcceptObservation => "observation.accept",
        CapabilityKey::AppendCorrection => "correction.chain.append",
        CapabilityKey::ApplyIdentitySeed => "identity.seed.apply",
        CapabilityKey::AttachIdentifier => "identity.identifier.attach",
        CapabilityKey::ConfigureListener => "listener.configure",
        CapabilityKey::CreateRecord => "identity.record.create",
        CapabilityKey::DeferReview => "identity.review.defer",
        CapabilityKey::DiscoverCapabilities => "system.capabilities.discover",
        CapabilityKey::EnrollFirstClient => "client.enroll",
        CapabilityKey::ExportWorkspace => "portability.workspace.export",
        CapabilityKey::InitializeNode => "node.initialize",
        CapabilityKey::InspectCorrectionChain => "correction.chain.inspect",
        CapabilityKey::InspectReview => "identity.review.inspect",
        CapabilityKey::ReplayReceipt => "receipt.replay",
        CapabilityKey::ResolveReview => "identity.review.resolve",
        CapabilityKey::RestoreWorkspace => "portability.workspace.restore",
        CapabilityKey::ResumeReview => "identity.review.resume",
        CapabilityKey::RevokeCredential => "credential.revoke",
        CapabilityKey::RotateCredential => "credential.rotate",
        CapabilityKey::SelectProfile => "profile.select",
        CapabilityKey::StreamReceipts => "receipt.stream",
        CapabilityKey::SystemHealth => "system.health",
        CapabilityKey::UploadEvidence => "evidence.upload",
        CapabilityKey::VerifyWorkspace => "portability.workspace.verify",
    }
}
