// This file is generated by `cargo xtask contract generate`. Do not edit.

use fasti_application::CapabilityKey;

/// Returns the registry-owned public ID for one internal application key.
pub const fn public_capability_id(key: CapabilityKey) -> &'static str {
    match key {
        CapabilityKey::AcceptObservation => "observation.accept",
        CapabilityKey::AppendCorrection => "correction.chain.append",
        CapabilityKey::AttachIdentifier => "identity.identifier.attach",
        CapabilityKey::ClearNuvioCollections => "profile.nuvio_collections.clear",
        CapabilityKey::ConfigureListener => "listener.configure",
        CapabilityKey::CreateBrowserSession => "browser.session.create",
        CapabilityKey::CreateRecord => "identity.record.create",
        CapabilityKey::DeferReview => "identity.review.defer",
        CapabilityKey::DeleteBrowserUser => "browser.user.delete",
        CapabilityKey::DiscoverCapabilities => "system.capabilities.discover",
        CapabilityKey::EndBrowserSession => "browser.session.end",
        CapabilityKey::EnrollFirstClient => "client.enroll",
        CapabilityKey::ExportWorkspace => "portability.workspace.export",
        CapabilityKey::GetNuvioCollections => "profile.nuvio_collections.get",
        CapabilityKey::InitializeNode => "node.initialize",
        CapabilityKey::InspectCorrectionChain => "correction.chain.inspect",
        CapabilityKey::InspectReview => "identity.review.inspect",
        CapabilityKey::ListBrowserUsers => "browser.user.list",
        CapabilityKey::ListRecords => "identity.record.list",
        CapabilityKey::ListTrackingDispositions => "profile.record.tracking_disposition.list",
        CapabilityKey::ReadBrowserSession => "browser.session.read",
        CapabilityKey::RegisterNamespace => "identity.namespace.register",
        CapabilityKey::ReplaceNuvioCollections => "profile.nuvio_collections.replace",
        CapabilityKey::ReplayReceipt => "receipt.replay",
        CapabilityKey::ResolveReview => "identity.review.resolve",
        CapabilityKey::RestoreWorkspace => "portability.workspace.restore",
        CapabilityKey::ResumeReview => "identity.review.resume",
        CapabilityKey::RevokeCredential => "credential.revoke",
        CapabilityKey::RotateCredential => "credential.rotate",
        CapabilityKey::SelectProfile => "profile.select",
        CapabilityKey::SetTrackingDisposition => "profile.record.tracking_disposition.set",
        CapabilityKey::StreamReceipts => "receipt.stream",
        CapabilityKey::SystemHealth => "system.health",
        CapabilityKey::UpdateBrowserUser => "browser.user.update",
        CapabilityKey::VerifyWorkspace => "portability.workspace.verify",
    }
}
