use anyhow::{ensure, Context};
use fasti_contracts::{HealthResponse, ProblemDetails};
use schemars::{generate::SchemaSettings, JsonSchema};
use serde_json::{Map, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use crate::registry;

pub(crate) type Artifacts = BTreeMap<PathBuf, Vec<u8>>;

const OPENAPI_PATH: &str = "contracts/generated/v1/openapi.json";
const CAPABILITY_REGISTRY_PATH: &str = "contracts/generated/v1/capabilities.json";
const HEALTH_SCHEMA_PATH: &str = "packages/schemas/schemas/health-response.json";
const PROBLEM_SCHEMA_PATH: &str = "packages/schemas/schemas/problem-details.json";

pub(crate) fn generate_checked_in(workspace_root: &Path) -> anyhow::Result<Artifacts> {
    generate_to(workspace_root, workspace_root)
}

pub(crate) fn generate_to(workspace_root: &Path, output_root: &Path) -> anyhow::Result<Artifacts> {
    let artifacts = build(workspace_root)?;
    write(output_root, &artifacts)?;
    Ok(artifacts)
}

pub(crate) fn verify_checked_in(
    workspace_root: &Path,
    generated: &Artifacts,
) -> anyhow::Result<()> {
    verify_inventory(workspace_root, generated)?;
    for (relative_path, expected) in generated {
        let checked_in_path = workspace_root.join(relative_path);
        let actual = fs::read(&checked_in_path).with_context(|| {
            format!(
                "generated artifact {} is absent; run `cargo xtask contract generate`",
                relative_path.display()
            )
        })?;
        ensure!(
            actual == *expected,
            "generated artifact {} is stale; run `cargo xtask contract generate`",
            relative_path.display()
        );
    }
    Ok(())
}

pub(crate) fn compare_outputs(
    first_root: &Path,
    second_root: &Path,
    first: &Artifacts,
    second: &Artifacts,
) -> anyhow::Result<()> {
    ensure!(
        first.keys().eq(second.keys()),
        "isolated contract generations produced different artifact inventories"
    );
    for relative_path in first.keys() {
        let first_bytes = fs::read(first_root.join(relative_path)).with_context(|| {
            format!(
                "first isolated generation omitted {}",
                relative_path.display()
            )
        })?;
        let second_bytes = fs::read(second_root.join(relative_path)).with_context(|| {
            format!(
                "second isolated generation omitted {}",
                relative_path.display()
            )
        })?;
        ensure!(
            first_bytes == second_bytes,
            "isolated contract generations differ at {}",
            relative_path.display()
        );
        ensure!(
            first.get(relative_path) == Some(&first_bytes)
                && second.get(relative_path) == Some(&second_bytes),
            "isolated generated bytes disagree with the in-memory artifact at {}",
            relative_path.display()
        );
    }
    Ok(())
}

fn build(workspace_root: &Path) -> anyhow::Result<Artifacts> {
    let mut artifacts = BTreeMap::new();
    insert(
        &mut artifacts,
        OPENAPI_PATH,
        serde_json::to_value(fasti_api::openapi()).context("OpenAPI is not serializable")?,
    )?;
    insert(
        &mut artifacts,
        CAPABILITY_REGISTRY_PATH,
        registry::normalized_public_json(workspace_root)?,
    )?;
    insert(
        &mut artifacts,
        HEALTH_SCHEMA_PATH,
        draft_2020_12_schema::<HealthResponse>()?,
    )?;
    insert(
        &mut artifacts,
        PROBLEM_SCHEMA_PATH,
        draft_2020_12_schema::<ProblemDetails>()?,
    )?;
    Ok(artifacts)
}

fn insert(artifacts: &mut Artifacts, relative_path: &str, value: Value) -> anyhow::Result<()> {
    let path = PathBuf::from(relative_path);
    ensure!(
        artifacts
            .insert(path.clone(), pretty_json(value)?)
            .is_none(),
        "duplicate generated artifact path {}",
        path.display()
    );
    Ok(())
}

fn draft_2020_12_schema<T: JsonSchema>() -> anyhow::Result<Value> {
    let schema = SchemaSettings::draft2020_12()
        .into_generator()
        .into_root_schema_for::<T>();
    let value = serde_json::to_value(schema).context("JSON Schema is not serializable")?;
    ensure!(
        value.get("$schema").and_then(Value::as_str)
            == Some("https://json-schema.org/draft/2020-12/schema"),
        "generated JSON Schema is not explicitly Draft 2020-12"
    );
    Ok(value)
}

fn pretty_json(value: Value) -> anyhow::Result<Vec<u8>> {
    let mut bytes = serde_json::to_vec_pretty(&sort_json(value))?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn sort_json(value: Value) -> Value {
    match value {
        Value::Object(object) => {
            let sorted: BTreeMap<_, _> = object
                .into_iter()
                .map(|(key, value)| (key, sort_json(value)))
                .collect();
            Value::Object(Map::from_iter(sorted))
        }
        Value::Array(values) => Value::Array(values.into_iter().map(sort_json).collect()),
        scalar => scalar,
    }
}

fn write(output_root: &Path, artifacts: &Artifacts) -> anyhow::Result<()> {
    for (relative_path, bytes) in artifacts {
        let destination = output_root.join(relative_path);
        let parent = destination
            .parent()
            .with_context(|| format!("generated path {} has no parent", destination.display()))?;
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
        fs::write(&destination, bytes)
            .with_context(|| format!("failed to write {}", destination.display()))?;
    }
    Ok(())
}

fn verify_inventory(output_root: &Path, expected: &Artifacts) -> anyhow::Result<()> {
    let directories: BTreeSet<_> = expected
        .keys()
        .filter_map(|path| path.parent().map(Path::to_path_buf))
        .collect();
    let mut actual = BTreeSet::new();
    for relative_directory in directories {
        let directory = output_root.join(&relative_directory);
        for entry in fs::read_dir(&directory)
            .with_context(|| format!("failed to inspect {}", directory.display()))?
        {
            let entry = entry?;
            let file_type = entry.file_type()?;
            ensure!(
                file_type.is_file(),
                "generated artifact directory {} contains non-file {}",
                relative_directory.display(),
                entry.path().display()
            );
            actual.insert(relative_directory.join(entry.file_name()));
        }
    }
    let expected_paths: BTreeSet<_> = expected.keys().cloned().collect();
    ensure!(
        actual == expected_paths,
        "checked-in generated artifact inventory differs: missing={:?}, unexpected={:?}",
        expected_paths.difference(&actual).collect::<Vec<_>>(),
        actual.difference(&expected_paths).collect::<Vec<_>>()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn artifact_inventory_is_fixed_and_unique() {
        let artifacts = build(workspace_root()).expect("contract generation succeeds");
        let actual: BTreeSet<_> = artifacts.keys().map(|path| path.as_path()).collect();
        let expected: BTreeSet<_> = [
            Path::new(OPENAPI_PATH),
            Path::new(CAPABILITY_REGISTRY_PATH),
            Path::new(HEALTH_SCHEMA_PATH),
            Path::new(PROBLEM_SCHEMA_PATH),
        ]
        .into_iter()
        .collect();
        assert_eq!(actual, expected);
    }

    #[test]
    fn generation_is_byte_reproducible() {
        let first = build(workspace_root()).expect("first generation succeeds");
        let second = build(workspace_root()).expect("second generation succeeds");
        assert_eq!(first, second);
        assert!(first.values().all(|artifact| artifact.ends_with(b"\n")));
    }

    fn workspace_root() -> &'static Path {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("xtask lives under workspace root")
    }
}
