name: OpenSSF Scorecard Supply-Chain Security

on:
  schedule:
    - cron: "30 1 * * 1" # Mondays at 01:30 UTC
  push:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard security analysis
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.2.2
        with:
          persist-credentials: false

      - name: "Run OpenSSF Scorecard"
        uses: ossf/scorecard-action@62b2cac7ed8198b15735db49cb1211a1a672f304 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false

      - name: "Upload artifact"
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: SARIF results
          path: results.sarif
          retention-days: 5
